// Generated by CoffeeScript 1.6.3
(function() {
  var PORT, fs, http, path, server, setting;

  http = require('http');

  path = require('path');

  fs = require('fs');

  PORT = 3000;

  setting = require('./config/setting');

  server = http.createServer(function(req, res) {
    var fileId, realPath;
    fileId = '12.png';
    realPath = path.resolve(setting.rootPath() + 'assets/files/' + fileId);
    console.log('realPaht: ' + realPath);
    return fs.exists(realPath, function(exists) {
      if (!exists) {
        return res.send('No exist!');
      } else {
        return fs.readFile(realPath, 'binary', function(err, file) {
          if (err) {
            res.writeHead(500, {
              'Content-Type': 'text/html'
            });
            return res.end(err);
          } else {
            res.writeHead(200, {
              'Content-Type': 'text/html'
            });
            res.write(file, 'binary');
            return res.end();
          }
        });
      }
    });
  });

  server.listen(PORT);

  console.log("Server runing at port: " + PORT + ".");

}).call(this);
