// Generated by CoffeeScript 1.6.3
/* respone file  binary for restful url
*/


(function() {
  var fs, http, mime, path, setting, zlib;

  http = require('http');

  path = require('path');

  fs = require('fs');

  zlib = require("zlib");

  setting = require('../config/setting');

  mime = require('../config/mime');

  exports.show = function(req, res) {
    var fileId, realPath;
    fileId = req.params.id;
    fileId = '12.png';
    realPath = path.resolve(setting.rootPath() + 'assets/files/' + fileId);
    /*
        ext = path.extname(realPath)
        ext = ext ? ext.slice(1)
        contentType = mime[ext] || "text/plain"
        res.set(200, {'Content-Type': contentType});
    */

    console.log('realPaht: ' + realPath);
    return fs.exists(realPath, function(exists) {
      var acceptEncoding, raw;
      if (!exists) {
        return res.send('No exist!');
      } else {
        raw = fs.createReadStream(realPath);
        acceptEncoding = req.headers['accept-encoding'] || "";
        if (acceptEncoding.match(/\bgzip\b/)) {
          res.set({
            'Content-Encoding': 'gzip'
          });
          return raw.pipe(zlib.createGzip()).pipe(res);
        } else if (acceptEncoding.match(/\bdeflate\b/)) {
          res.set({
            'Content-Encoding': 'gzip'
          });
          return raw.pipe(zlib.createDeflate()).pipe(res);
        } else {
          res.set(200, "Ok");
          return raw.pipe(res);
        }
      }
    });
  };

}).call(this);
