// Generated by CoffeeScript 1.6.3
/*
   project settings
*/


(function() {
  exports.rootPath = function() {
    var rootRealPath;
    return rootRealPath = __dirname + '/../';
  };

}).call(this);
